# Generated by Django 4.1.4 on 2023-01-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, unique=True)),
                ('describe', models.CharField(max_length=100)),
                ('time_remaning', models.CharField(max_length=10)),
            ],
        ),
    ]
